name: Maven
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for Maven
        uses: LucaFeger/action-maven-cli@1.1.0
        args: "clean package"